# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 219a08577f5837b0792a2b1d217d9301a4fbeea912ed9f3bcad828130bf8ff0f24a76ca7338c3635ed6d5728d71c25656f8b4d246799547a47a3396aa6cdce7b

test:
  secret_key_base: b6cfaf1e7330219f592f96833053db78273d4bda796333c91064148cd90687e237985c73d33065c9d473f20a91fceebcf4c31c902229eb4737fbf7538bef4a2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
